# @file
#
#  Common General hardware
#
#  SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
#
#  SPDX-License-Identifier: BSD-2-Clause-Patent
#

config SOC_GENERAL
  bool
  imply SUPPORTS_NVIDIA_SDHCI
  imply SUPPORTS_NETWORKING_DEVICE_NVIDIA
  imply SUPPORTS_SOC_USB
  imply SUPPORTS_NVIDIA_DISPLAY
  imply FIRMWARE_PARTITION_SUPPORT
  imply USE_GENERAL_FIRMWARE_CAPSULE_SIZE
  imply SUPPORTS_PREPI_MODE
  imply SUPPORTS_ARM_PSCI_MP_SERVICE
  imply SUPPORTS_TEGRA_PLATFORM_CONFIG
  imply SUPPORTS_TEGRA_SPI
  imply SUPPORTS_BPMP
  imply SUPPORTS_TEGRA_I2C
  imply SUPPORTS_TEGRA_GPIO
